import { api } from "../api";

const itemAuth = api.injectEndpoints({
    endpoints: (builder) => ({
        addItem: builder.mutation({
            query: (values) => ({
                url: '/v2/item/add_item',
                method: 'POST',
                body: values,
            }),
        }),
      
        allItem: builder.query({
            query: () => ({
                url: '/v2/item/all_item',
                method: 'GET',
            }),
        }),
    }),
});

// Correctly exporting the hooks generated by `injectEndpoints`
export const { useAddItemMutation, useAllItemQuery } = itemAuth;
