import { api } from "../api";

const orderAuth = api.injectEndpoints({
    endpoints: (builder) => ({
        addOrder: builder.mutation({
            query: (values) => ({
                url: '/v3/order/add_order',
                method: 'POST',
                body: values,
            }),
        }),
      
        allOrder: builder.query({
            query: () => ({
                url: '/v3/order/all_orders',
                method: 'GET',
            }),
        }),
    }),
});

// Correctly exporting the hooks generated by `injectEndpoints`
export const { useAddOrderMutation, useAllOrderQuery } = orderAuth;
